# This script extends "Node" and acts as a global Autoload singleton (accessible everywhere as "Global").
# It manages global game state: economy/coins, inventory references, player lifetime stats, 
# visitor tracking, guest pet reviews, and global save/load persistence.
extends Node

# ==========================================
# PRELOADS & SIGNALS
# ==========================================
# Preloads the player's shared inventory resource file.
@onready var inv: Inventory = preload("res://source/inventory/player_inv.tres")

# Signal emitted whenever the coin balance changes so UI counters (like CoinDisplay) can update instantly.
signal coinsChanged(value)

# ==========================================
# ECONOMY & SETTERS
# ==========================================
# Uses GDScript's custom setter (`set(new_value)`) to automatically track lifetime earnings/spending 
# whenever `Global.coins` is updated anywhere in code.
var coins: int = 0:
	set(new_value):
		# If coins decreased, record the spent difference.
		if (coins > new_value):
			totalCoinsSpent += coins - new_value
		# If coins increased, record the earned difference.
		else:
			totalCoinsEarned += new_value - coins
		coins = new_value
		# Broadcast the updated coin balance to UI listeners.
		emit_signal('coinsChanged', coins)

# Lifetime financial tracking metrics.
var totalCoinsEarned: int = coins
var totalCoinsSpent: int = 0

# ==========================================
# VISITOR & PERFORMANCE STATS
# ==========================================
# History tracking for visiting guest pets across all rooms.
var visitors: Array = []
var totalVisitors: int = 0
var uniqueVisitors: Array = []
var totalUniqueVisitors: int = 0
var averageHappiness: int = 0

# Array storing historical stay summary dictionaries and review entries generated by PetGuestManager.
var reviewsInfo: Array = []

# ==========================================
# INITIALIZATION
# ==========================================
func _ready():
	# Registers this node in the "SaveGroup" group so SaveManager can include it in save operations.
	add_to_group("SaveGroup")
	
	# Connects inventory updates to a debug printing function.
	inv.update.connect(print_items)

# ==========================================
# SAVE / LOAD SYSTEM INTEGRATION
# ==========================================
# Called by SaveManager during save operations to package global state into a SavedGlobal object.
func on_save_game(saved_data: Array[SavedData]):
	var my_data = SavedGlobal.new()
	my_data.coins = coins
	my_data.totalCoinsEarned = totalCoinsEarned
	my_data.totalCoinsSpent = totalCoinsSpent
	my_data.visitors = visitors
	my_data.totalVisitors = totalVisitors
	my_data.totalUniqueVisitors = totalUniqueVisitors
	my_data.averageHappiness = averageHappiness
	my_data.reviewsInfo = reviewsInfo
	my_data.inv_slots = inv.slots
	saved_data.append(my_data)

# Called by SaveManager during load operations to restore global state from SavedGlobal.
func on_load_game(saved_data: SavedData):
	coins = saved_data.coins
	totalCoinsEarned = saved_data.totalCoinsEarned
	totalCoinsSpent = saved_data.totalCoinsSpent
	visitors = saved_data.visitors
	totalVisitors = saved_data.totalVisitors
	totalUniqueVisitors = saved_data.totalUniqueVisitors
	averageHappiness = saved_data.averageHappiness
	reviewsInfo = saved_data.reviewsInfo
	update_inv_slots(saved_data.inv_slots)

# Rebuilds the inventory slot array using saved slot data.
func update_inv_slots(inv_slots: Array[InvSlot]):
	inv.slots = []
	for slot in inv_slots:
		var new_slot = InvSlot.new()
		new_slot.item = slot.item
		new_slot.amount = slot.amount
		inv.slots.append(new_slot)

# ==========================================
# INVENTORY & ITEM HELPERS
# ==========================================
# Adds an Item resource into the player's global inventory.
func collect(item):
	print(item.name, 'added to inventory')
	inv.insert(item)

# Debug helper to print current inventory contents to the Godot Output console.
func print_items():
	for slot in inv.slots:
		if slot.item:
			if slot.item.name:
				print(slot.item.name, slot.amount)
			else:
				print('item name not found')
		else:
			print('empty slot')

# ==========================================
# STAT TRACKING FUNCTIONS
# ==========================================
# Records a new visiting pet species and updates total/unique visitor metrics.
func add_visitor_to_array(new_visitor):
	print('new visitor:', new_visitor)
	visitors.append(new_visitor)
	if (new_visitor not in uniqueVisitors):
		uniqueVisitors.append(new_visitor)
		totalUniqueVisitors = uniqueVisitors.size()
	totalVisitors = visitors.size()
